# Generated by Django 5.0.1 on 2024-02-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
