# Generated by Django 5.0.1 on 2024-02-02 13:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_created_date_alter_article_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subarticle',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subarticle',
            name='low_article',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subarticle',
            name='top_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
