# Generated by Django 5.0.1 on 2024-02-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_subarticle_title_alter_subarticle_low_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article/comments'),
        ),
    ]
