# Generated by Django 5.0.1 on 2024-01-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_aboutme_address_alter_aboutme_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='date',
            field=models.DateField(),
        ),
    ]
