# Generated by Django 5.0.1 on 2024-01-30 13:04

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutme_email_aboutme_image_aboutme_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ImageField(max_length=25, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='main/partner/images')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_education', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, default=1, help_text='Please enter your phone number', max_length=31),
            preserve_default=False,
        ),
    ]
