# Generated by Django 5.0.1 on 2024-02-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_aboutme_created_date_alter_award_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/about'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/partner/images'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='media/images/project'),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.ImageField(upload_to='media/images/services'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='Last_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skills',
            name='Last_week',
            field=models.IntegerField(),
        ),
    ]
