# Generated by Django 5.0.1 on 2024-02-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_aboutme_image_alter_partner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/about'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(null=True, upload_to='main/partner'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='main/project'),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.ImageField(upload_to='main/services'),
        ),
    ]
