# Generated by Django 5.0.1 on 2024-02-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_mecontact_li_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecontact',
            name='web_site',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
