# Generated by Django 5.0.1 on 2024-02-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_mecontact_web_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mecontact',
            name='email_link',
        ),
    ]
